# GitHub Labeler
# https://github.com/marketplace/actions/github-labeler

# default
- name: bug
  color: d73a4a
  description: Something isn't working
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed
- name: invalid
  color: e4e669
  description: This doesn't seem right
- name: question
  color: d876e3
  description: Further information is requested
- name: wontfix
  color: ffffff
  description: This will not be worked on

# custom - Git convention
- name: feat
  color: 2593fa
  description: "Git convention: feat"
- name: refactor
  color: FBCA04
  description: "Git convention: refactor"
- name: test
  color: FBCA04
  description: "Git convention: test"
- name: ci
  color: ededed
  description: "Git convention: ci"
- name: build
  color: ededed
  description: "Git convention: build"
- name: style
  color: ededed
  description: "Git convention: style"
- name: chore
  color: ededed
  description: "Git convention: chore"
- name: fix
  color: d73a4a
  description: "Git convention: fix"
- name: docs
  color: 0075ca
  description: "Git convention: docs"

# custom - Semantic versioning
- name: major
  color: E99695
  description: "Semantic versioning: major"
- name: minor
  color: F9D0C4
  description: "Semantic versioning: minor"
- name: patch
  color: FEF2C0
  description: "Semantic versioning: patch"
